export default [
  {words: ["cop", "cut", "cat"], spellWord: "c_aah_t", correctWord: "cat"},
  {words: ["mom", "map", "mop"], spellWord: "m_ooh_m", correctWord: "mom", wordsOnly: true},
  {words: ["bell", "ill", "fall"], spellWord: "iih_l", correctWord: "ill", wordsOnly: true},
  {words: ["in", "on", "off"], spellWord: "ooh_n", correctWord: "on", wordsOnly: true},
  {words: ["bat", "beg", "bug"], spellWord: "b_uuh_g", correctWord: "bug", wordsOnly: true},
  {words: ["lip", "lap", "loop"], spellWord: "l_iih_p", correctWord: "lip", wordsOnly: true},
  {words: ["fist", "fan", "fat"], spellWord: "f_aah_t", correctWord: "fat", wordsOnly: true},
  {words: ["moon", "men", "map"], spellWord: "m_eeh_n", correctWord: "men", wordsOnly: true},
  {words: ["road", "bread", "red"], spellWord: "r_eeh_d", correctWord: "red", wordsOnly: true},
  {words: ["shin", "ship", "chin"], spellWord: "sh_iih_n", correctWord: "shin", wordsOnly: true},
  {words: ["nap", "nut", "knight"], spellWord: "n_uuh_t", correctWord: "nut", wordsOnly: true},
  {words: ["cent", "sit", "sip"], spellWord: "s_iih_t", correctWord: "sit", wordsOnly: true},
  {words: ["rug", "rag", "wreck"], spellWord: "r_uuh_g", correctWord: "rug", wordsOnly: true},
  {words: ["fish", "fast", "fist"], spellWord: "f_iih_s_t", correctWord: "fist", wordsOnly: true},
  {words: ["chop", "chip", "shop"], spellWord: "ch_ooh_p", correctWord: "chop", wordsOnly: true},
  {words: ["flag", "flip", "slip"], spellWord: "f_l_iih_p", correctWord: "flip", wordsOnly: true},
  {words: ["stick", "stack", "shack"], spellWord: "s_t_aah_k", correctWord: "stack", wordsOnly: true},
  {words: ["truck", "trick", "trunk"], spellWord: "t_r_uuh_k", correctWord: "truck", wordsOnly: true},
  {words: ["spin", "spoon", "sing"], spellWord: "s_p_iih_n", correctWord: "spin", wordsOnly: true}
];
