export default [
  {words: ["cat", "cut", "hat"], correctWords: ["cat", "hat"], incorrectPhonic: "uh", correctPhonic: "ah"},
  {words: ["sit", "wig", "bus"], correctWords: ["sit", "wig"], incorrectPhonic: "uh", correctPhonic: "ih", shortInstructions: true},
  {words: ["run", "leg", "bed"], correctWords: ["leg", "bed"], incorrectPhonic: "uh", correctPhonic: "eh", shortInstructions: true},
  {words: ["bug", "cub", "box"], correctWords: ["bug", "cub"], incorrectPhonic: "oh", correctPhonic: "uh", shortInstructions: true},
  {words: ["mad", "mop", "cat"], correctWords: ["mad", "cat"], incorrectPhonic: "oh", correctPhonic: "ah", shortInstructions: true},
  {words: ["wet", "hit", "hill"], correctWords: ["hit", "hill"], incorrectPhonic: "eh", correctPhonic: "ih", shortInstructions: true},
  {words: ["pet", "zip", "desk"], correctWords: ["pet", "desk"], incorrectPhonic: "ih", correctPhonic: "eh", shortInstructions: true},
  {words: ["mud", "hot", "rug"], correctWords: ["mud", "rug"], incorrectPhonic: "oh", correctPhonic: "uh", shortInstructions: true},
  {words: ["sit", "set", "red"], correctWords: ["set", "red"], incorrectPhonic: "ih", correctPhonic: "eh", shortInstructions: true},
  {words: ["pin", "pen", "lip"], correctWords: ["pin", "lip"], incorrectPhonic: "eh", correctPhonic: "ih", shortInstructions: true},
  {words: ["fox", "bud", "gull"], correctWords: ["bud", "gull"], incorrectPhonic: "oh", correctPhonic: "uh", shortInstructions: true},
  {words: ["clock", "truck", "drop"], correctWords: ["clock", "drop"], incorrectPhonic: "uh", correctPhonic: "oh", shortInstructions: true},
  {words: ["ship", "dish", "chef"], correctWords: ["ship", "dish"], incorrectPhonic: "eh", correctPhonic: "ih", shortInstructions: true},
  {words: ["feather", "bread", "path"], correctWords: ["feather", "bread"], incorrectPhonic: "ah", correctPhonic: "eh", shortInstructions: true},
  {words: ["stick", "truck", "trick"], correctWords: ["stick", "trick"], incorrectPhonic: "uh", correctPhonic: "ih", shortInstructions: true},
  {words: ["strap", "stop", "knot"], correctWords: ["stop", "knot"], incorrectPhonic: "ah", correctPhonic: "oh", shortInstructions: true},
  {words: ["brush", "bridge", "puddle"], correctWords: ["brush", "puddle"], incorrectPhonic: "ih", correctPhonic: "uh", shortInstructions: true},
  {words: ["treasure", "head", "ladder"], correctWords: ["treasure", "head"], incorrectPhonic: "ah", correctPhonic: "eh", shortInstructions: true},
  {words: ["crumb", "crab", "tongue"], correctWords: ["crumb", "tongue"], incorrectPhonic: "ah", correctPhonic: "uh", shortInstructions: true},
  {words: ["sled", "pitch", "vest"], correctWords: ["sled", "vest"], incorrectPhonic: "ih", correctPhonic: "eh", shortInstructions: true}
];
