export default [
  {words: ["cat", "cut", "hat"], correctWords: ["cat", "hat"], incorrectPhonic: "uh", correctPhonic: "ah"},
  {words: ["sit", "wig", "bus"], correctWords: ["sit", "wig"], incorrectPhonic: "uh", correctPhonic: "ih", wordsOnly: true},
  {words: ["run", "hen", "bed"], correctWords: ["hen", "bed"], incorrectPhonic: "uh", correctPhonic: "eh", wordsOnly: true},
  {words: ["bug", "sun", "box"], correctWords: ["bug", "sun"], incorrectPhonic: "oh", correctPhonic: "uh", wordsOnly: true},
  {words: ["mad", "mop", "cat"], correctWords: ["mad", "cat"], incorrectPhonic: "oh", correctPhonic: "ah", wordsOnly: true},
  {words: ["wet", "hit", "hill"], correctWords: ["hit", "hill"], incorrectPhonic: "eh", correctPhonic: "ih", wordsOnly: true},
  {words: ["pet", "zip", "desk"], correctWords: ["pet", "desk"], incorrectPhonic: "ih", correctPhonic: "eh", wordsOnly: true},
  {words: ["mud", "hot", "rug"], correctWords: ["mud", "rug"], incorrectPhonic: "oh", correctPhonic: "uh", wordsOnly: true},
  {words: ["sit", "set", "red"], correctWords: ["set", "red"], incorrectPhonic: "ih", correctPhonic: "eh", wordsOnly: true},
  {words: ["pin", "pen", "lip"], correctWords: ["pin", "lip"], incorrectPhonic: "eh", correctPhonic: "ih", wordsOnly: true},
  {words: ["fox", "bud", "fun"], correctWords: ["bud", "fun"], incorrectPhonic: "oh", correctPhonic: "uh", wordsOnly: true},
  {words: ["clock", "truck", "drop"], correctWords: ["clock", "drop"], incorrectPhonic: "uh", correctPhonic: "oh", wordsOnly: true},
  {words: ["ship", "dish", "chef"], correctWords: ["ship", "dish"], incorrectPhonic: "eh", correctPhonic: "ih", wordsOnly: true},
  {words: ["feather", "bread", "father"], correctWords: ["feather", "bread"], incorrectPhonic: "ah", correctPhonic: "eh", wordsOnly: true},
  {words: ["stick", "truck", "trick"], correctWords: ["stick", "trick"], incorrectPhonic: "uh", correctPhonic: "ih", wordsOnly: true},
  {words: ["strap", "stop", "knot"], correctWords: ["stop", "knot"], incorrectPhonic: "ah", correctPhonic: "oh", wordsOnly: true},
  {words: ["brush", "bridge", "puddle"], correctWords: ["brush", "puddle"], incorrectPhonic: "ih", correctPhonic: "uh", wordsOnly: true},
  {words: ["treasure", "head", "ladder"], correctWords: ["treasure", "head"], incorrectPhonic: "ah", correctPhonic: "eh", wordsOnly: true},
  {words: ["crumb", "crab", "tongue"], correctWords: ["crumb", "tongue"], incorrectPhonic: "ah", correctPhonic: "uh", wordsOnly: true},
  {words: ["sled", "pitch", "bench"], correctWords: ["sled", "bench"], incorrectPhonic: "ih", correctPhonic: "eh", wordsOnly: true},
];
