export default [
  {words: ["up", "in", "on"], correctWord: "up"},
  {words: ["igloo", "ugly", "eagle"], correctWord: "ugly", wordsOnly: true},
  {words: ["enter", "otter", "under"], correctWord: "under", wordsOnly: true},
  {words: ["cup", "cop", "cap"], correctWord: "cup", wordsOnly: true},
  {words: ["beg", "bag", "bug"], correctWord: "bug", wordsOnly: true},
  {words: ["rug", "rag", "rig"], correctWord: "rug", wordsOnly: true},
  {words: ["run", "ring", "rain"], correctWord: "run", wordsOnly: true},
  {words: ["top", "tape", "tub"], correctWord: "tub", wordsOnly: true},
  {words: ["fin", "fan", "fun"], correctWord: "fun", wordsOnly: true},
  {words: ["hat", "hut", "hot"], correctWord: "hut", wordsOnly: true},
  {words: ["boys", "bees", "bus"], correctWord: "bus", wordsOnly: true},
  {words: ["nut", "net", "knot"], correctWord: "nut", wordsOnly: true},
  {words: ["trick", "truck", "track"], correctWord: "truck", wordsOnly: true},
  {words: ["lunch", "launch", "blond"], correctWord: "lunch", wordsOnly: true},
  {words: ["batter", "boater", "butter"], correctWord: "butter", wordsOnly: true},
  {words: ["rest", "rush", "wrench"], correctWord: "rush", wordsOnly: true},
  {words: ["stomp", "stamp", "stump"], correctWord: "stump", wordsOnly: true},
  {words: ["mud", "mad", "mitt"], correctWord: "mud", wordsOnly: true},
  {words: ["bench", "punch", "pitch"], correctWord: "punch", wordsOnly: true},
  {words: ["duck", "dock", "deck"], correctWord: "duck", wordsOnly: true}
];
