export default [
  {words: ["hop", "dog", "hot"], correctWords: ["hop", "hot"]},
  {words: ["box", "socks", "boy"], correctWords: ["box", "boy"], shortInstructions: true},
  {words: ["ring", "mad", "monkey"], correctWords: ["mad", "monkey"], shortInstructions: true},
  {words: ["chop", "itch", "chin"], correctWords: ["chop", "chin"], shortInstructions: true},
  {words: ["read", "bear", "rose"], correctWords: ["read", "rose"], shortInstructions: true},
  {words: ["trash", "desk", "dish"], correctWords: ["desk", "dish"], shortInstructions: true},
  {words: ["pot", "pig", "top"], correctWords: ["pot", "pig"], shortInstructions: true},
  {words: ["violin", "fin", "vase"], correctWords: ["violin", "vase"], shortInstructions: true},
  {words: ["flag", "frog", "gopher"], correctWords: ["flag", "frog"], shortInstructions: true},
  {words: ["moth", "thumb", "thorn"], correctWords: ["thumb", "thorn"], shortInstructions: true},
  {words: ["swing", "ice", "stick"], correctWords: ["swing", "stick"], shortInstructions: true},
  {words: ["trick", "drink", "table"], correctWords: ["trick", "table"], shortInstructions: true},

  {words: ["map", "mad", "lip"], correctWords: ["map", "lip"], endingIntro: true, ending: true},
  {words: ["fish", "fist", "fast"], correctWords: ["fist", "fast"], ending: true, shortInstructions: true},
  {words: ["man", "mom", "jam"], correctWords: ["mom", "jam"], ending: true, shortInstructions: true},
  {words: ["itch", "dish", "trash"], correctWords: ["dish", "trash"], ending: true, shortInstructions: true},
  {words: ["sleep", "sheep", "sheet"], correctWords: ["sleep", "sheep"], ending: true, shortInstructions: true},
  {words: ["milk", "spill", "talk"], correctWords: ["milk", "talk"], ending: true, shortInstructions: true},
  {words: ["hand", "desk", "yard"], correctWords: ["hand", "yard"], ending: true, shortInstructions: true},
  {words: ["string", "sink", "tongue"], correctWords: ["string", "tongue"], ending: true, shortInstructions: true},
  {words: ["blue", "shoe", "boot"], correctWords: ["blue", "shoe"], ending: true, shortInstructions: true},
  {words: ["snow", "boat", "piano"], correctWords: ["snow", "piano"], ending: true, shortInstructions: true},
  {words: ["play", "pail", "spray"], correctWords: ["play", "spray"], ending: true, shortInstructions: true},
  {words: ["cowboy", "oyster", "fur"], correctWords: ["oyster", "fur"], ending: true, shortInstructions: true}
];
