export default [
  {words: ["in", "on", "off"], correctWord: "in"},
  {words: ["bell", "ill", "tall"], correctWord: "ill", wordsOnly: true},
  {words: ["rug", "rag", "rig"], correctWord: "rig", wordsOnly: true},
  {words: ["bug", "beg", "big"], correctWord: "big", wordsOnly: true},
  {words: ["pin", "pen", "pan"], correctWord: "pin", wordsOnly: true},
  {words: ["lap", "lip", "loop"], correctWord: "lip", wordsOnly: true},
  {words: ["flip", "flap", "flop"], correctWord: "flip", wordsOnly: true},
  {words: ["boot", "beet", "bit"], correctWord: "bit", wordsOnly: true},
  {words: ["spine", "spoon", "spin"], correctWord: "spin", wordsOnly: true},
  {words: ["peg", "pig", "pug"], correctWord: "pig", wordsOnly: true},
  {words: ["punch", "pitch", "bench"], correctWord: "pitch", wordsOnly: true},
  {words: ["Bob", "Bill", "Ben"], correctWord: "Bill", wordsOnly: true},
  {words: ["bed", "bad", "bid"], correctWord: "bid", wordsOnly: true},
  {words: ["slide", "sled", "slip"], correctWord: "slip", wordsOnly: true},
  {words: ["pit", "pet", "putt"], correctWord: "pit", wordsOnly: true},
  {words: ["watch", "itch", "wrench"], correctWord: "itch", wordsOnly: true},
  {words: ["chess", "chips", "cheese"], correctWord: "chips", wordsOnly: true},
  {words: ["ships", "shapes", "shops"], correctWord: "ships", wordsOnly: true},
  {words: ["eagle", "igloo", "ugly"], correctWord: "igloo", wordsOnly: true},
  {words: ["injured", "elm", "under"], correctWord: "injured", wordsOnly: true}
];
