export default [
  {letters: ["o", "u"], word: "bug", correctLetter: "u", activityType: 1},
  {letters: ["e", "a"], word: "mad", correctLetter: "a", activityType: 1, shortInstructions: true},
  {letters: ["o", "u"], word: "cop", correctLetter: "o", activityType: 1, shortInstructions: true},
  {letters: ["a", "e"], word: "red", correctLetter: "e", activityType: 1, shortInstructions: true},
  {letters: ["i", "u"], word: "pin", correctLetter: "i", activityType: 1, shortInstructions: true},
  {letters: ["e", "a"], word: "bat", correctLetter: "a", activityType: 1, shortInstructions: true},
  {letters: ["u", "o"], word: "box", correctLetter: "o", activityType: 1, shortInstructions: true},
  {letters: ["o", "u"], word: "sun", correctLetter: "u", activityType: 1, shortInstructions: true},
  {letters: ["e", "i"], word: "jet", correctLetter: "e", activityType: 1, shortInstructions: true},
  {letters: ["i", "a"], word: "fish", correctLetter: "i", activityType: 1, shortInstructions: true},
  {letters: ["a", "o"], word: "hop", correctLetter: "o", activityType: 1, shortInstructions: true},
  {letters: ["i", "e"], word: "ten", correctLetter: "e", activityType: 1, shortInstructions: true},
  {letters: ["o", "i"], word: "pill", correctLetter: "i", activityType: 1, shortInstructions: true},
  {letters: ["a", "o"], word: "lap", correctLetter: "a", activityType: 1, shortInstructions: true},
  {letters: ["u", "o"], word: "hug", correctLetter: "u", activityType: 1, shortInstructions: true},

  {words: ["cat", "cut"], letter: "a", correctWord: "cat", activityType: 2},
  {words: ["bed", "bad"], letter: "e", correctWord: "bed", activityType: 2, shortInstructions: true},
  {words: ["tip", "tap"], letter: "i", correctWord: "tip", activityType: 2, shortInstructions: true},
  {words: ["sock", "sick"], letter: "o", correctWord: "sock", activityType: 2, shortInstructions: true},
  {words: ["fan", "fun"], letter: "u", correctWord: "fun", activityType: 2, shortInstructions: true},
  {words: ["bell", "ball"], letter: "e", correctWord: "bell", activityType: 2, shortInstructions: true},
  {words: ["hut", "hot"], letter: "o", correctWord: "hot", activityType: 2, shortInstructions: true},
  {words: ["bug", "bag"], letter: "u", correctWord: "bug", activityType: 2, shortInstructions: true},
  {words: ["lap", "lip"], letter: "i", correctWord: "lip", activityType: 2, shortInstructions: true},
  {words: ["bed", "bad"], letter: "a", correctWord: "bad", activityType: 2, shortInstructions: true},
  {words: ["pen", "pan"], letter: "e", correctWord: "pen", activityType: 2, shortInstructions: true},
  {words: ["lick", "lake"], letter: "i", correctWord: "lick", activityType: 2, shortInstructions: true},
  {words: ["cap", "cup"], letter: "u", correctWord: "cup", activityType: 2, shortInstructions: true},
  {words: ["knit", "knot"], letter: "i", correctWord: "knit", activityType: 2, shortInstructions: true},
  {words: ["beg", "big"], letter: "e", correctWord: "beg", activityType: 2, shortInstructions: true}
];
