export default [
  {letters: ["a", "o", "u"], word: "bug", correctLetter: "u", activityType: 1},
  {letters: ["e", "a", "i"], word: "mad", correctLetter: "a", activityType: 1, shortInstructions: true},
  {letters: ["o", "u", "a"], word: "cop", correctLetter: "o", activityType: 1, shortInstructions: true},
  {letters: ["a", "e", "u"], word: "red", correctLetter: "e", activityType: 1, shortInstructions: true},
  {letters: ["i", "o", "u"], word: "pin", correctLetter: "i", activityType: 1, shortInstructions: true},
  {letters: ["e", "a", "i"], word: "bat", correctLetter: "a", activityType: 1, shortInstructions: true},
  {letters: ["u", "o", "a"], word: "box", correctLetter: "o", activityType: 1, shortInstructions: true},
  {letters: ["e", "o", "u"], word: "sun", correctLetter: "u", activityType: 1, shortInstructions: true},
  {letters: ["e", "i", "o"], word: "jet", correctLetter: "e", activityType: 1, shortInstructions: true},
  {letters: ["i", "u", "a"], word: "fish", correctLetter: "i", activityType: 1, shortInstructions: true},
  {letters: ["u", "a", "o"], word: "hop", correctLetter: "o", activityType: 1, shortInstructions: true},
  {letters: ["i", "a", "e"], word: "ten", correctLetter: "e", activityType: 1, shortInstructions: true},
  {letters: ["o", "u", "i"], word: "pill", correctLetter: "i", activityType: 1, shortInstructions: true},
  {letters: ["e", "a", "o"], word: "lap", correctLetter: "a", activityType: 1, shortInstructions: true},
  {letters: ["u", "o", "a"], word: "hug", correctLetter: "u", activityType: 1, shortInstructions: true},

  {words: ["cat", "cut", "coat"], letter: "a", correctWord: "cat", activityType: 2},
  {words: ["bud", "bed", "bad"], letter: "e", correctWord: "bed", activityType: 2, shortInstructions: true},
  {words: ["tip", "tap", "top"], letter: "i", correctWord: "tip", activityType: 2, shortInstructions: true},
  {words: ["sack", "sock", "sick"], letter: "o", correctWord: "sock", activityType: 2, shortInstructions: true},
  {words: ["fin", "fan", "fun"], letter: "u", correctWord: "fun", activityType: 2, shortInstructions: true},
  {words: ["bell", "ball", "bull"], letter: "e", correctWord: "bell", activityType: 2, shortInstructions: true},
  {words: ["hat", "hut", "hot"], letter: "o", correctWord: "hot", activityType: 2, shortInstructions: true},
  {words: ["bug", "bag", "big"], letter: "u", correctWord: "bug", activityType: 2, shortInstructions: true},
  {words: ["lap", "lip", "leap"], letter: "i", correctWord: "lip", activityType: 2, shortInstructions: true},
  {words: ["baby", "bed", "bad"], letter: "a", correctWord: "bad", activityType: 2, shortInstructions: true},
  {words: ["pin", "pen", "pan"], letter: "e", correctWord: "pen", activityType: 2, shortInstructions: true},
  {words: ["lock", "lick", "lake"], letter: "i", correctWord: "lick", activityType: 2, shortInstructions: true},
  {words: ["cap", "cup", "cape"], letter: "u", correctWord: "cup", activityType: 2, shortInstructions: true},
  {words: ["knit", "knot", "net"], letter: "i", correctWord: "knit", activityType: 2, shortInstructions: true},
  {words: ["bug", "beg", "big"], letter: "e", correctWord: "beg", activityType: 2, shortInstructions: true}
];
