export default [
  {words: ["cat", "cut", "kite"], correctWord: "cat"},
  {words: ["beg", "bag", "big"], correctWord: "bag"},
  {words: ["bud", "bed", "bad"], correctWord: "bad"},
  {words: ["mud", "mad", "mitt"], correctWord: "mad"},
  {words: ["hit", "hot", "hat"], correctWord: "hat"},
  {words: ["cap", "cop", "cup"], correctWord: "cap"},
  {words: ["bit", "beet", "bat"], correctWord: "bat"},
  {words: ["lap", "lip", "loop"], correctWord: "lap"},
  {words: ["pin", "pen", "pan"], correctWord: "pan"},
  {words: ["dig", "drag", "dog"], correctWord: "drag"},
  {words: ["mop", "map", "men"], correctWord: "map"},
  {words: ["flap", "flip", "flop"], correctWord: "flap"},
  {words: ["fish", "fast", "foot"], correctWord: "fast"},
  {words: ["rest", "rush", "rash"], correctWord: "rash"},
  {words: ["track", "trick", "trunk"], correctWord: "track"},
  {words: ["badge", "bridge", "edge"], correctWord: "badge"},
  {words: ["enter", "under", "actor"], correctWord: "actor"},
  {words: ["string", "stretch", "strap"], correctWord: "strap"},
  {words: ["screen", "scratch", "screw"], correctWord: "scratch"}
];
