#!/bin/bash

mkdir -p pngs

for f in tiffs/*
do
  fname=${f##*/}
  name=${fname%%.*}
  src="tiffs/$name.tif"
  dest="pngs/$name.png"
  echo "Converting $src to $dest"
  convert "tiffs/$name.tif" "pngs/$name.png" 2> /dev/null
done
