#!/bin/bash
# Run this file from the project's root directory using `npm run setup-cordova`

PROJECT_DIR=$(pwd)
CORDOVA_DIR="$PROJECT_DIR/builds/cordova"

cd "$CORDOVA_DIR"
cordova prepare
cordova build
