export default [
  {words: ["in", "on", "end"], correctWord: "in"},
  {words: ["bug", "beg", "big"], correctWord: "big"},
  {words: ["fin", "fan", "fun"], correctWord: "fin"},
  {words: ["pin", "pen", "pan"], correctWord: "pin"},
  {words: ["lap", "lip", "loop"], correctWord: "lip"},
  {words: ["sip", "sap", "soup"], correctWord: "sip"},
  {words: ["boot", "beet", "bit"], correctWord: "bit"},
  {words: ["spin", "spoon", "spray"], correctWord: "spin"},
  {words: ["peg", "pig", "pug"], correctWord: "pig"},
  {words: ["punch", "pitch", "bench"], correctWord: "pitch"},
  {words: ["Ben", "Bob", "Bill"], correctWord: "Bill"},
  {words: ["bed", "bad", "bid"], correctWord: "bid"},
  {words: ["sleep", "sled", "slip"], correctWord: "slip"},
  {words: ["pit", "pet", "putt"], correctWord: "pit"},
  {words: ["pal", "pill", "pool"], correctWord: "pill"},
  {words: ["chess", "chips", "cheese"], correctWord: "chips"},
  {words: ["ships", "shapes", "shops"], correctWord: "ships"},
  {words: ["eagle", "igloo", "ugly"], correctWord: "igloo"},
  {words: ["injured", "enter", "under"], correctWord: "injured"}
];
